name: root
channels:
- conda-forge
- defaults
dependencies:
- matplotlib=2.0.2=py35_2
- numpy=1.13.1=py35_0
- pandas=0.20.3=py35_1
- pint=0.8.1=py35_0
- scipy=0.19.1=np113py35_0
- seaborn=0.7.1=py35_0
- tabulate=0.7.7=py35_0