 name: root
 channels:
 - conda-forge
 - defaults
 dependencies:
 - matplotlib=3.0.3=py35_2
 - numpy=1.13.1=py35_0
 - scipy=0.19.1=np113py35_0
 - sphinxcontrib-bibtex=0.3.6=py35_0
 - openpyxl=2.5.0b1=py35_0
 
