name: root
channels:
- conda-forge
- defaults
dependencies:
- matplotlib=2.1.0=py35_1
- numpy=1.11.1=py35_1
- scipy=0.18.0=np111py35_0
- seaborn=0.7.1=py35_0
- tabulate=0.7.5=py35_0
- sphinxcontrib-bibtex=0.3.6=py35_0
- graphviz=2.38.0=7
